### PR TITLE
java-runtime: stream client call listener back-pressure

### PR DESCRIPTION
**Pull request by ahjohannessen**
- only request for more messages when stream is being pulled instead
   of unconditionally request for more through `onMessage`.

 - current behavior causes heap to fill up and eventually cause
   out of memory exceptions.

 - add test that showcases we only request more messages when there
   is a demand.

### CODE REVIEW

**Review by rossabaker — APPROVED** [review]

**Comment by rossabaker** [comment]
Could you request n upfront, and then still one-at-a-time to replenish?  Still not optimal, but simple, but you'd have a better chance of maintaining a buffer until a more sophisticated strategy is created.

**Comment by ahjohannessen** [comment]
Not sure. I am thinking that this PR loss in throughput could be replenished via. stream combinators. I posted a, rather incomplete, suggestion in the gitter channel.

**Comment by rossabaker** [comment]
Yeah, all the prefetches are probably a fine interim solution, but we'll still be `request`ing 1 at a time.  I don't know enough about the runtime to know how much faster it is to `request(100)` if we can really accept 100.  Your high-low idea could work, as it would be able to request batches.

I think this is fine as is to solve the crash.

**Comment by ahjohannessen** [comment]
I am fine with the loss in throughput now, as downstream using `groupWithin` makes up for it when considering downstream probably uses IO like db inserts or similar that take longer time. Perhaps my idea on gitter could be amended to this, but it is probably needs more tests.

**Comment by ahjohannessen** [comment]
Thanks Ross :)

**Pull request merged**
