### PR TITLE
[WIP] Experiments with performance

### PR DESCRIPTION
**Pull request by nikiforo**
I benchmarked using this command:
`GRPC_BENCHMARK_WARMUP=20s GRPC_BENCHMARK_DURATION=40s ./bench.sh scala_fs2_bench`

ORIGINAL(fs2-grpc 1.1.5)
```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| scala_fs2                   |    2558 |      316.62 ms |      572.77 ms |      786.95 ms |         1.01 s |  106.58% |    221.16 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
```

fs2-grpc main
3d63db8d8a71e9a5102848f90e578841700c0718
```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| scala_fs2                   |    2202 |      405.11 ms |      641.56 ms |      864.58 ms |         1.33 s |  103.79% |    229.26 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
```

Channel instead of ce Queue
69b855f17309484eab51bcebe2ba9056c29adaa9
```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| scala_fs2                   |    2161 |      410.97 ms |      669.56 ms |      844.99 ms |         1.61 s |  104.27% |    232.76 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
```

For now every update makes situation worse

### CODE REVIEW

**Comment by ahjohannessen** [comment]
I think `StreamIngest` is not used in the benchmarks given that:

```
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}
```

is unary / unary. So that is a bit odd.

**Comment by nikiforo** [comment]
unary listener without fs2.Stream
2390ad79103baa842ac1f770c54a50bec35bb24a
```
-----------------------------------------------------------------------------------------------------------------------------------------
| name                        |   req/s |   avg. latency |        90 % in |        95 % in |        99 % in | avg. cpu |   avg. memory |
-----------------------------------------------------------------------------------------------------------------------------------------
| scala_fs2                   |    2239 |      390.23 ms |      681.94 ms |      762.23 ms |         1.52 s |  104.82% |     236.3 MiB |
-----------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ahjohannessen** [comment]
@nikiforo This could perhaps be of interest: https://github.com/typelevel/fs2-grpc/pull/394

**Comment by djspiewak** [comment]
Trying to capture some thoughts…

The `unsafeRunSync`s are almost certainly the largest source of trouble here. Reading through `ServerCall`'s javadoc a bit, it doesn't seem like we're *required* to hard-block the calling thread, merely allowed to do so. Removing the blocking altogether would pretty dramatically improve throughput and lower context shift penalties. In the one or two places where the code is relying on sequentialization due to blocking, you can reestablish that by wrapping the sequentially-next action in `Sync[F].delay(...)` and just `flatMap`ping with the dispatched action.

Once you've done this, you should be able to reduce the threads used by io-grpc down to an absolute minim. The ideal (in my measurements) is somewhere around 1-2 threads, because you're looking at something which is purely IO-bound and just responsible for grabbing data and shoveling it off into the compute pool. This will also reduce a lot of the context shift penalties since thread affinity will improve a lot.

Finally, you need to find a way to reestablish backpressure guarantees that have been lost by making the listener non-blocking. I'm not sure exactly how to do this in io-grpc, but the documentation suggests that there should be a way given that they allow the listeners to be non-blocking in the first place. What you're looking for is basically something like Netty's `setAutoRead` and `read()`, which controls the paging of the next block of bytes from the underlying IO system and allows you to explicitly track and control when it's safe to do exactly that.

On the multiple call handler, it seems most likely that a higher performance `Queue` would help alleviate a major bottleneck, since CE's `Queue` right now is about an order of magnitude slower than it strictly needs to be.

**Comment by ahjohannessen** [comment]
@djspiewak I did an experiment by redoing the unary to unary call [here](https://github.com/typelevel/fs2-grpc/pull/486/files#).

**Comment by ahjohannessen** [comment]
I am closing this as performance work by @naoh87 that improves this has been merged into main.

**Pull request closed without merging**
